@echo off
rem taskkling launcher (t-htr1): find a usable binary, first hit wins --
rem   1. this checkout's own pin      .taskkling\bin  (from `taskkling init --local-bin`)
rem   2. TASKKLING_BINARY             explicit override (same env var the UI honors)
rem   3. the main checkout's pin      worktrees, via `git rev-parse --git-common-dir`
rem   4. taskkling.exe on PATH        global install (.exe only, so this .cmd never recurses)
rem Regenerated by `init --local-bin` (core LocalBin.kt) -- keep both copies identical.
setlocal
set "TK=%~dp0.taskkling\bin\taskkling.exe"
if exist "%TK%" goto :run
set "TK=%TASKKLING_BINARY%"
if defined TASKKLING_BINARY if exist "%TK%" goto :run
set "COMMON="
for /f "delims=" %%G in ('git -C "%~dp0." rev-parse --git-common-dir 2^>nul') do set "COMMON=%%G"
if not defined COMMON goto :path
if "%COMMON%"==".git" goto :path
for %%G in ("%COMMON%") do set "TK=%%~dpG.taskkling\bin\taskkling.exe"
if exist "%TK%" goto :run
:path
set "TK="
for /f "delims=" %%G in ('where taskkling.exe 2^>nul') do if not defined TK set "TK=%%G"
if defined TK goto :run
echo taskkling: no binary found (tried .taskkling\bin, TASKKLING_BINARY, the main checkout's pin, PATH) 1>&2
echo fix: install taskkling (install.ps1) or pin one with "taskkling init --local-bin" 1>&2
exit /b 9009
:run
"%TK%" %*
exit /b %errorlevel%
