plugins {
    alias(libs.plugins.kotlinMultiplatform)
}

// --- Version single-sourcing -------------------------------------------------
// Kotlin/Native binaries have no runtime resource access, so the tool version
// must be baked in as a compile-time constant. We generate a tiny Kotlin source
// file holding `BUILD_VERSION` from the Gradle `project.version` (which derives
// from the `version` property in gradle.properties) and add it to commonMain so
// every target — native + jvm — compiles the same value.
val generateVersionFile by tasks.registering {
    val versionValue = project.version.toString()
    val outDir = layout.buildDirectory.dir("generated/version")
    inputs.property("version", versionValue)
    outputs.dir(outDir)
    doLast {
        val pkgDir = outDir.get().asFile.resolve("io/taskkling/core")
        pkgDir.mkdirs()
        pkgDir.resolve("Version.kt").writeText(
            """
            // GENERATED by the :core `generateVersionFile` Gradle task — do not edit.
            // Source of truth: the `version` property in gradle.properties.
            package io.taskkling.core

            internal const val BUILD_VERSION: String = "$versionValue"
            """.trimIndent() + "\n",
        )
    }
}

// Belt-and-suspenders: registering the task's output dir as a source directory
// (below) already wires the implicit dependency, but make every Kotlin compile
// task depend on generation explicitly so it runs first for all targets incl. jvm.
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateVersionFile)
}

kotlin {
    jvm()

    mingwX64()
    macosArm64()
    macosX64()
    linuxX64()

    applyDefaultHierarchyTemplate()

    sourceSets {
        // Shared actual for the POSIX file lock (`flock`): linux + macOS. Windows
        // (mingw) uses LockFileEx in its own leaf source set; JVM uses FileChannel.
        val posixMain by creating { dependsOn(commonMain.get()) }
        named("linuxX64Main") { dependsOn(posixMain) }
        named("macosX64Main") { dependsOn(posixMain) }
        named("macosArm64Main") { dependsOn(posixMain) }

        // Compile the generated Version.kt (BUILD_VERSION) into every target.
        // Passing the task provider wires the compile-task dependency implicitly.
        commonMain {
            kotlin.srcDir(generateVersionFile)
        }

        commonMain.dependencies {
            api(project(":contract"))
            implementation(libs.okio)
            implementation(libs.kotlinx.datetime)
        }

        // Pure, target-agnostic unit tests (frontmatter, compute, slug, datetime,
        // id) run on every target; CI invokes the JVM variant (:core:jvmTest).
        // Workspace/golden tests use a JVM temp dir, so they live in jvmTest and
        // inherit the same kotlin-test runner.
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.serialization.json) // golden tests encode the export DTO
        }
    }
}
