package io.taskkling.core

import okio.FileSystem
import okio.Path
import okio.Path.Companion.toPath

/** Outcome of [installLocalBin]: where the binary landed and the wrappers written. */
public data class LocalBinResult(
    val binary: Path,
    val wrappers: List<Path>,
    val version: String,
)

/**
 * The `./taskkling` (POSIX) wrapper (t-htr1): a binary RESOLUTION CHAIN, first
 * hit wins, mirroring the UI's CliDiscovery order — the checkout's own pin,
 * `TASKKLING_BINARY`, the main checkout's pin (so the wrapper works from a
 * fresh git worktree, where `.taskkling/` is git-ignored and absent), then
 * PATH, then a clear error. A local pin beats the main checkout's (a deliberate
 * worktree pin wins); the main checkout's beats PATH (the repo-pinned version
 * beats a possibly-lagging global install). Resolution only picks the BINARY —
 * which store it acts on stays with cwd workspace discovery, so borrowing the
 * main checkout's binary can never bind a worktree to the main store.
 *
 * The tracked repo-root copies of both wrappers must stay byte-identical to
 * these constants (LocalBinWrapperTest); `.gitattributes` pins `/taskkling` to
 * LF and `*.cmd` to CRLF, so the comparison is deterministic on every platform.
 */
internal val POSIX_WRAPPER: String = listOf(
    "#!/bin/sh",
    "# taskkling launcher (t-htr1): find a usable binary, first hit wins --",
    "#   1. this checkout's own pin      .taskkling/bin  (from `taskkling init --local-bin`)",
    "#   2. TASKKLING_BINARY             explicit override (same env var the UI honors)",
    "#   3. the main checkout's pin      worktrees, via `git rev-parse --git-common-dir`",
    "#   4. taskkling on PATH            global install (self-recursion guarded)",
    "# Regenerated by `init --local-bin` (core LocalBin.kt) -- keep both copies identical.",
    "dir=\"\$(CDPATH= cd -- \"\$(dirname -- \"\$0\")\" && pwd)\"",
    "for exe in \"\$dir/.taskkling/bin/taskkling\" \"\$dir/.taskkling/bin/taskkling.exe\"; do",
    "    if [ -x \"\$exe\" ]; then exec \"\$exe\" \"\$@\"; fi",
    "done",
    "if [ -n \"\${TASKKLING_BINARY:-}\" ] && [ -x \"\$TASKKLING_BINARY\" ]; then",
    "    exec \"\$TASKKLING_BINARY\" \"\$@\"",
    "fi",
    "common=\"\$(git -C \"\$dir\" rev-parse --git-common-dir 2>/dev/null)\"",
    "if [ -n \"\$common\" ] && [ \"\$common\" != \".git\" ]; then",
    "    main=\"\$(dirname -- \"\$common\")\"",
    "    for exe in \"\$main/.taskkling/bin/taskkling\" \"\$main/.taskkling/bin/taskkling.exe\"; do",
    "        if [ -x \"\$exe\" ]; then exec \"\$exe\" \"\$@\"; fi",
    "    done",
    "fi",
    "found=\"\$(command -v taskkling 2>/dev/null || true)\"",
    "if [ -n \"\$found\" ] && [ \"\$found\" != \"\$0\" ] && [ \"\$found\" != \"\$dir/taskkling\" ]; then",
    "    exec \"\$found\" \"\$@\"",
    "fi",
    "echo \"taskkling: no binary found (tried ./.taskkling/bin, TASKKLING_BINARY, the main checkout's pin, PATH)\" >&2",
    "echo \"fix: install taskkling (install.sh / install.ps1) or pin one with 'taskkling init --local-bin'\" >&2",
    "exit 127",
).joinToString("\n", postfix = "\n")

/**
 * The `taskkling.cmd` (Windows) wrapper: the same chain as [POSIX_WRAPPER] in
 * cmd.exe batch. PATH lookup asks `where` for `taskkling.exe` only, so this
 * `.cmd` can never find and re-enter itself. CRLF line endings throughout
 * (cmd.exe batch parsing has LF edge cases; see `.gitattributes`).
 */
internal val CMD_WRAPPER: String = listOf(
    "@echo off",
    "rem taskkling launcher (t-htr1): find a usable binary, first hit wins --",
    "rem   1. this checkout's own pin      .taskkling\\bin  (from `taskkling init --local-bin`)",
    "rem   2. TASKKLING_BINARY             explicit override (same env var the UI honors)",
    "rem   3. the main checkout's pin      worktrees, via `git rev-parse --git-common-dir`",
    "rem   4. taskkling.exe on PATH        global install (.exe only, so this .cmd never recurses)",
    "rem Regenerated by `init --local-bin` (core LocalBin.kt) -- keep both copies identical.",
    "setlocal",
    "set \"TK=%~dp0.taskkling\\bin\\taskkling.exe\"",
    "if exist \"%TK%\" goto :run",
    "set \"TK=%TASKKLING_BINARY%\"",
    "if defined TASKKLING_BINARY if exist \"%TK%\" goto :run",
    "set \"COMMON=\"",
    "for /f \"delims=\" %%G in ('git -C \"%~dp0.\" rev-parse --git-common-dir 2^>nul') do set \"COMMON=%%G\"",
    "if not defined COMMON goto :path",
    "if \"%COMMON%\"==\".git\" goto :path",
    "for %%G in (\"%COMMON%\") do set \"TK=%%~dpG.taskkling\\bin\\taskkling.exe\"",
    "if exist \"%TK%\" goto :run",
    ":path",
    "set \"TK=\"",
    "for /f \"delims=\" %%G in ('where taskkling.exe 2^>nul') do if not defined TK set \"TK=%%G\"",
    "if defined TK goto :run",
    "echo taskkling: no binary found (tried .taskkling\\bin, TASKKLING_BINARY, the main checkout's pin, PATH) 1>&2",
    "echo fix: install taskkling (install.ps1) or pin one with \"taskkling init --local-bin\" 1>&2",
    "exit /b 9009",
    ":run",
    "\"%TK%\" %*",
    "exit /b %errorlevel%",
).joinToString("\r\n", postfix = "\r\n")

/**
 * Self-install the running binary into a per-project `.taskkling/bin/` and drop
 * `./taskkling` (POSIX) + `./taskkling.cmd` (Windows) wrappers at [root], so the
 * project carries its own pinned tool (`init --local-bin`, PRD §6.2). Steps:
 *
 *  1. copy [currentExecutablePath] to `root/.taskkling/bin/<basename>` and mark
 *     it executable (the basename is `taskkling.exe` on Windows, `taskkling`
 *     elsewhere — taken from the running executable);
 *  2. stamp `root/.taskkling/bin/.version` with [Taskkling.VERSION] (pins what
 *     was installed);
 *  3. write BOTH wrapper scripts regardless of host, so a cross-platform
 *     checkout has each: [POSIX_WRAPPER] and [CMD_WRAPPER], each resolving a
 *     binary by the documented chain (the freshly copied pin is their first hit).
 *
 * Idempotent: existing copies and wrappers are overwritten.
 *
 * Refuses the one self-destructive case: the running binary IS the resolved
 * dest (`init --local-bin` invoked through the in-repo wrapper resolves to the
 * PINNED copy, so it would try to reinstall itself). See the [source] overload.
 */
public fun installLocalBin(root: Path): LocalBinResult =
    installLocalBin(root, currentExecutablePath().toPath())

/**
 * [installLocalBin] with the running executable to pin passed explicitly — the
 * testable seam (a unit test can point [source] at the computed dest to exercise
 * the self-overwrite guard without a locked Windows image).
 *
 * The guard (t-1g3t): if [source] canonicalizes to the same file as the dest,
 * the copy below is both meaningless (copying a file onto itself) AND
 * destructive — `fs.delete(dest)` would unlink the very binary we copy FROM
 * (POSIX allows unlinking a running image), and on Windows the live `.exe` is
 * locked and the raw copy surfaces a bare, unactionable "Permission denied".
 * This is the stale-pinned-binary trap: a pinned copy can't reinstall itself,
 * so we fail early with a message that names the file and the way out.
 */
internal fun installLocalBin(root: Path, source: Path): LocalBinResult {
    val fs = FileSystem.SYSTEM
    val basename = source.name // taskkling.exe on Windows, taskkling elsewhere

    val binDir = root / ".taskkling" / "bin"
    fs.createDirectories(binDir)

    val dest = binDir / basename

    // Same canonicalized-equality check `update` uses to tell self from other
    // (Main.kt's isSelf), guarding a copy instead of a self-replace.
    fun canon(p: Path): Path = try { fs.canonicalize(p) } catch (_: Exception) { p }
    if (canon(source) == canon(dest)) {
        throw TkError(
            ExitCode.VALIDATION,
            "cannot reinstall taskkling over its own running binary ($dest) — you're running the " +
                "pinned copy itself, which can't overwrite its own image. Refresh it from another " +
                "install: run the global binary by full path ('<taskkling> init --local-bin') or " +
                "'taskkling update --local'.",
        )
    }

    fs.delete(dest, mustExist = false)
    fs.copy(source, dest)
    markExecutable(dest.toString())

    fs.write(binDir / ".version") { writeUtf8(Taskkling.VERSION + "\n") }

    val posixWrapper = root / "taskkling"
    fs.write(posixWrapper) { writeUtf8(POSIX_WRAPPER) }
    markExecutable(posixWrapper.toString())

    val cmdWrapper = root / "taskkling.cmd"
    fs.write(cmdWrapper) { writeUtf8(CMD_WRAPPER) }

    return LocalBinResult(dest, listOf(posixWrapper, cmdWrapper), Taskkling.VERSION)
}
